data:
  dataset_folder: data
  train_dataset: train.csv
  val_dataset: dev.csv
  test_dataset: test.csv
  use_id: False

tokenizer:
  padding: max_length
  max_length: 512
  truncation: True
  return_attention_mask: True

text_embedding:
  type: pretrained
  add_new_token: False
  text_encoder: MoritzLaurer/mDeBERTa-v3-base-mnli-xnli  # Pre-trained for NLI!
  freeze: False
  use_lora: False
  lora_target_modules: ["query_proj", "key_proj", "value_proj"]  # DeBERTa modules
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  d_features: 768
  d_model: 768  # Keep original dimension
  dropout: 0.1

model:
  type_model: pretrained_nli
  dropout: 0.1

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 10  # Fewer epochs since pre-trained
  patience: 3
  learning_rate: 1.0e-5  # Lower LR for pre-trained
  weight_decay: 0.01
  metric_for_best_model: f1
  per_device_train_batch_size: 8   # Conservative for 512 tokens
  per_device_valid_batch_size: 8

inference:
  test_dataset: data/test.csv
  batch_size: 32
