data:
  dataset_folder: data
  train_dataset: train.csv
  val_dataset: dev.csv
  test_dataset: test.csv
  use_id: False

tokenizer:
  padding: max_length
  max_length: 256
  truncation: True
  return_attention_mask: True

text_embedding:
  type: pretrained
  add_new_token: False
  text_encoder: MoritzLaurer/mDeBERTa-v3-base-mnli-xnli  # Vietnamese BERT
  freeze: False
  use_lora: False
  lora_target_modules: ["query", "value", "key"]
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  d_features: 768
  d_model: 512
  dropout: 0.1

model:
  type_model: cross_attention
  d_model: 512
  num_heads: 8
  dropout: 0.1

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 30
  patience: 5
  learning_rate: 2.0e-5
  weight_decay: 0.01
  metric_for_best_model: f1
  per_device_train_batch_size: 16
  per_device_valid_batch_size: 16

inference:
  test_dataset: data/test.csv
  batch_size: 64
