data:
  dataset_folder: data
  train_dataset: train.csv
  val_dataset: dev.csv
  test_dataset: test.csv
  use_id: False

tokenizer:
  padding: max_length
  max_length: 512  # Shorter for sentence-level tasks
  truncation: True
  return_attention_mask: True

text_embedding:
  type: pretrained
  add_new_token: False
  text_encoder: vinai/phobert-base
  freeze: False
  use_lora: True  # Enable LoRA for efficiency
  lora_target_modules: ["query", "value", "key"]
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  d_features: 768
  d_model: 512
  dropout: 0.1

model:
  type_model: sbert
  pooling_method: mean  # Options: mean, max, cls
  dropout: 0.1

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 20
  patience: 5
  learning_rate: 2.0e-5
  weight_decay: 0.01
  metric_for_best_model: f1
  per_device_train_batch_size: 32  # Can use larger batch for SBERT
  per_device_valid_batch_size: 32

inference:
  test_dataset: data/test.csv
  batch_size: 128
