data:
  dataset_folder: data
  train_dataset: train.csv
  val_dataset: dev.csv
  test_dataset: test.csv
  use_id: False

tokenizer:
  padding: max_length
  max_length: 2048     # Extra long context for very long documents
  truncation: True
  return_attention_mask: True

text_embedding:
  type: pretrained
  add_new_token: False
  text_encoder: microsoft/deberta-v2-xlarge-mnli  # XL model for maximum performance
  freeze: False
  use_lora: True       # Essential for XL model
  lora_target_modules: ["query_proj", "key_proj", "value_proj", "dense"]
  lora_r: 32           # Higher rank for XL model
  lora_alpha: 64       # Higher alpha
  lora_dropout: 0.1
  d_features: 1536     # DeBERTa-XL hidden size
  d_model: 1536        # Keep original dimension
  dropout: 0.1

model:
  type_model: pretrained_nli
  dropout: 0.1

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 3   # Very few epochs for XL model
  patience: 1           # Early patience
  learning_rate: 1.0e-6 # Very low LR for XL model
  weight_decay: 0.01
  metric_for_best_model: f1
  per_device_train_batch_size: 1   # Micro batch for XL + 2048 tokens
  per_device_valid_batch_size: 1
  gradient_accumulation_steps: 32   # Large accumulation

inference:
  test_dataset: data/test.csv
  batch_size: 1         # Single sample inference
